services:
  postgres: # Update
    image: postgres:alpine
    container_name: postgres # Update
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Update

  redis: # Update
    image: redis:alpine
    container_name: redis # Update
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data # Update

networks:
  default:
    name: nestjs # Update

volumes:
  postgres_data: # Update
  redis_data: # Update
